export const disasterSceneConfig = {
  flood: {
    heroGradient: "from-sky-950 via-blue-800 to-cyan-500",
    mediaSrc: "/disasters/flood.jpg",
    soundSrc: "/sounds/flood-rain.mp3",
    overlay: "bg-slate-950/45",
    effect: "water",
    title: "Flood Alert",
    headline: "Flood conditions are being monitored in real time.",
    meterLabel: "Water Level",
    meterUnit: "m",
    primaryReading: "Rainfall",
    primaryUnit: "mm",
    secondaryReading: "River Flow",
    secondaryUnit: "m³/s",
    infoStripBg: "bg-sky-100/95",
    infoStripBorder: "border-sky-200",
    infoStripText: "text-white",
    tips: [
      "Move to higher ground if water levels rise.",
      "Do not walk or drive through floodwater.",
      "Prepare emergency items and monitor local updates.",
    ],
  },

  landslide: {
    heroGradient: "from-stone-950 via-amber-800 to-orange-500",
    mediaSrc: "/disasters/landslide.jpg",
    soundSrc: "/sounds/landslide-rumble.mp3",
    overlay: "bg-black/45",
    effect: "dust",
    title: "Landslide Alert",
    headline: "Slope instability is being monitored.",
    meterLabel: "Slope Risk",
    meterUnit: "%",
    primaryReading: "Soil Moisture",
    primaryUnit: "%",
    secondaryReading: "Ground Movement",
    secondaryUnit: "mm/h",
    infoStripBg: "bg-amber-100/95",
    infoStripBorder: "border-amber-200",
    infoStripText: "text-white",
    tips: [
      "Stay away from steep slopes and unstable ground.",
      "Leave immediately if you see falling debris.",
      "Avoid roads near landslide-prone areas.",
    ],
  },

  wildfire: {
    heroGradient: "from-red-950 via-orange-800 to-yellow-500",
    mediaSrc: "/disasters/wildfire.jpg",
    soundSrc: "/sounds/fire-crackle.mp3",
    overlay: "bg-black/50",
    effect: "embers",
    title: "Wildfire Alert",
    headline: "Heat and smoke conditions are active.",
    meterLabel: "Fire Intensity",
    meterUnit: "%",
    primaryReading: "Temperature",
    primaryUnit: "°C",
    secondaryReading: "Smoke Density",
    secondaryUnit: "%",
    infoStripBg: "bg-red-100/95",
    infoStripBorder: "border-red-200",
    infoStripText: "text-white",
    tips: [
      "Move away from smoke and follow evacuation orders.",
      "Keep exit routes clear.",
      "Close doors and windows if smoke is heavy.",
    ],
  },

  storm: {
    heroGradient: "from-slate-950 via-indigo-900 to-blue-500",
    mediaSrc: "/disasters/storm.jpg",
    soundSrc: "/sounds/storm-thunder.mp3",
    overlay: "bg-slate-950/50",
    effect: "rain",
    title: "Storm Alert",
    headline: "Severe weather conditions remain active.",
    meterLabel: "Storm Intensity",
    meterUnit: "%",
    primaryReading: "Wind Speed",
    primaryUnit: "km/h",
    secondaryReading: "Rainfall",
    secondaryUnit: "mm",
    infoStripBg: "bg-indigo-100/95",
    infoStripBorder: "border-indigo-200",
    infoStripText: "text-white",
    tips: [
      "Stay indoors and away from windows.",
      "Avoid unnecessary travel.",
      "Secure loose outdoor items.",
    ],
  },

  cyclone: {
    heroGradient: "from-slate-950 via-cyan-900 to-sky-500",
    mediaSrc: "/disasters/cyclone.jpg",
    soundSrc: "/sounds/cyclone-wind.mp3",
    overlay: "bg-slate-950/50",
    effect: "wind",
    title: "Cyclone Alert",
    headline: "Cyclone conditions are intensifying.",
    meterLabel: "Cyclone Strength",
    meterUnit: "%",
    primaryReading: "Wind Speed",
    primaryUnit: "km/h",
    secondaryReading: "Pressure Drop",
    secondaryUnit: "hPa",
    infoStripBg: "bg-cyan-100/95",
    infoStripBorder: "border-cyan-200",
    infoStripText: "text-white",
    tips: [
      "Remain indoors and follow official evacuation guidance.",
      "Stay away from exposed coastal areas.",
      "Keep phones charged and supplies ready.",
    ],
  },

  tsunami: {
    heroGradient: "from-blue-950 via-teal-800 to-cyan-500",
    mediaSrc: "/disasters/tsunami.jpg",
    soundSrc: "/sounds/ocean-roar.mp3",
    overlay: "bg-blue-950/50",
    effect: "water",
    title: "Tsunami Alert",
    headline: "Coastal hazard conditions are being monitored.",
    meterLabel: "Wave Threat",
    meterUnit: "%",
    primaryReading: "Sea Level Change",
    primaryUnit: "m",
    secondaryReading: "Wave Speed",
    secondaryUnit: "km/h",
    infoStripBg: "bg-teal-100/95",
    infoStripBorder: "border-teal-200",
    infoStripText: "text-teal-900",
    tips: [
      "Move immediately to higher ground.",
      "Do not remain near the coast.",
      "Use official evacuation routes.",
    ],
  },

  drought: {
    heroGradient: "from-yellow-950 via-amber-800 to-orange-500",
    mediaSrc: "/disasters/drought.jpg",
    soundSrc: "/sounds/hot-wind.mp3",
    overlay: "bg-yellow-950/35",
    effect: "heat",
    title: "Drought Alert",
    headline: "Dry conditions and water stress are active.",
    meterLabel: "Drought Severity",
    meterUnit: "%",
    primaryReading: "Temperature",
    primaryUnit: "°C",
    secondaryReading: "Water Reserve",
    secondaryUnit: "%",
    infoStripBg: "bg-yellow-100/95",
    infoStripBorder: "border-yellow-200",
    infoStripText: "text-white",
    tips: [
      "Conserve water and follow restrictions.",
      "Avoid heat exposure during peak hours.",
      "Monitor local supply announcements.",
    ],
  },

  heatwave: {
    heroGradient: "from-orange-950 via-red-800 to-yellow-500",
    mediaSrc: "/disasters/heatwave.jpg",
    soundSrc: "/sounds/hot-wind.mp3",
    overlay: "bg-orange-950/35",
    effect: "heat",
    title: "Heatwave Alert",
    headline: "Extreme heat conditions are being monitored.",
    meterLabel: "Heat Risk",
    meterUnit: "%",
    primaryReading: "Temperature",
    primaryUnit: "°C",
    secondaryReading: "Humidity",
    secondaryUnit: "%",
    infoStripBg: "bg-orange-100/95",
    infoStripBorder: "border-orange-200",
    infoStripText: "text-white0",
    tips: [
      "Stay hydrated and avoid direct sun exposure.",
      "Reduce outdoor activity during hottest hours.",
      "Check on vulnerable people.",
    ],
  },

  earthquake: {
    heroGradient: "from-black via-stone-800 to-slate-500",
    mediaSrc: "/disasters/earthquake.jpg",
    soundSrc: "/sounds/earthquake-rumble.mp3",
    overlay: "bg-black/45",
    effect: "shake",
    title: "Earthquake Alert",
    headline: "Ground activity remains under observation.",
    meterLabel: "Seismic Risk",
    meterUnit: "%",
    primaryReading: "Aftershock Index",
    primaryUnit: "%",
    secondaryReading: "Ground Activity",
    secondaryUnit: "µm/s",
    infoStripBg: "bg-stone-100/95",
    infoStripBorder: "border-stone-200",
    infoStripText: "text-white",
    tips: [
      "Stay away from damaged buildings.",
      "Be prepared for aftershocks.",
      "Follow evacuation and safety advice.",
    ],
  },

  volcanic: {
    heroGradient: "from-black via-red-950 to-orange-600",
    mediaSrc: "/disasters/volcanic.jpg",
    soundSrc: "/sounds/volcanic-rumble.mp3",
    overlay: "bg-black/50",
    effect: "embers",
    title: "Volcanic Activity Alert",
    headline: "Volcanic conditions are elevated.",
    meterLabel: "Eruption Risk",
    meterUnit: "%",
    primaryReading: "Ash Density",
    primaryUnit: "%",
    secondaryReading: "Ground Tremor",
    secondaryUnit: "µm/s",
    infoStripBg: "bg-zinc-100/95",
    infoStripBorder: "border-zinc-200",
    infoStripText: "text-white",
    tips: [
      "Avoid ash-affected zones.",
      "Use face covering if ash is present.",
      "Prepare for evacuation if instructed.",
    ],
  },

  blizzard: {
    heroGradient: "from-slate-950 via-blue-900 to-slate-300",
    mediaSrc: "/disasters/blizzard.jpg",
    soundSrc: "/sounds/blizzard-wind.mp3",
    overlay: "bg-slate-950/45",
    effect: "snow",
    title: "Blizzard Alert",
    headline: "Snowstorm conditions remain severe.",
    meterLabel: "Blizzard Severity",
    meterUnit: "%",
    primaryReading: "Snowfall",
    primaryUnit: "cm",
    secondaryReading: "Wind Chill",
    secondaryUnit: "°C",
    infoStripBg: "bg-slate-100/95",
    infoStripBorder: "border-slate-200",
    infoStripText: "text-white",
    tips: [
      "Avoid travel unless essential.",
      "Stay indoors and protect against extreme cold.",
      "Keep emergency heating supplies ready.",
    ],
  },

  default: {
    heroGradient: "from-slate-950 via-slate-800 to-slate-500",
    mediaSrc: "/disasters/default.jpg",
    soundSrc: "",
    overlay: "bg-black/40",
    effect: "pulse",
    title: "Natural Disaster Alert",
    headline: "Hazard conditions are being monitored.",
    meterLabel: "Risk Level",
    meterUnit: "%",
    primaryReading: "Primary Reading",
    primaryUnit: "",
    secondaryReading: "Secondary Reading",
    secondaryUnit: "",
    infoStripBg: "bg-slate-100/95",
    infoStripBorder: "border-slate-200",
    infoStripText: "text-white",
    tips: [
      "Follow official instructions carefully.",
      "Stay informed using trusted updates.",
      "Avoid unnecessary travel in affected areas.",
    ],
  },
};

export function getDisasterTypeKey(type = "") {
  const value = String(type).trim().toLowerCase();

  if (value.includes("flood")) return "flood";
  if (value.includes("landslide")) return "landslide";
  if (value.includes("fire") || value.includes("wildfire")) return "wildfire";
  if (value.includes("storm")) return "storm";
  if (value.includes("cyclone")) return "cyclone";
  if (value.includes("tsunami")) return "tsunami";
  if (value.includes("drought")) return "drought";
  if (value.includes("heat")) return "heatwave";
  if (value.includes("earthquake")) return "earthquake";
  if (value.includes("volcan")) return "volcanic";
  if (value.includes("blizzard") || value.includes("snow")) return "blizzard";

  return "default";
}