import {
  Waves,
  Mountain,
  Flame,
  CloudLightning,
  Wind,
  ThermometerSun,
  AlertTriangle,
  Volcano,
  CloudRain,
  Snowflake,
} from "lucide-react";

export const disasterVisualConfig = {
  flood: {
    key: "flood",
    title: "Flood Alert",
    icon: Waves,
    pageBg: "bg-sky-50",
    heroGradient: "from-sky-950 via-blue-800 to-cyan-500",
    accent: "text-cyan-100",
    panelBg: "bg-slate-950/78",
    meterCardBg: "bg-slate-950/82",
    readingCardBg: "bg-blue-950/70",
    infoStripBg: "bg-sky-100",
    infoStripBorder: "border-sky-200",
    infoStripText: "text-sky-900",
    sectionTint: "bg-sky-50",
    sectionBorder: "border-sky-200",
    meterLabel: "Water Level",
    meterUnit: "m",
    thresholdLabel: "Danger Level",
    meterColor: "bg-cyan-400",
    primaryReading: "Rainfall",
    primaryUnit: "mm",
    secondaryReading: "River Flow",
    secondaryUnit: "m³/s",
    headline: "Flood waters are being monitored in real time.",
    description:
      "This page shows the latest live-style flood readings, current risk level, and what people in the area should do now.",
    publicTips: [
      "Move to higher ground if water levels rise.",
      "Do not walk or drive through floodwater.",
      "Prepare essential items and monitor local updates.",
    ],
  },

  landslide: {
    key: "landslide",
    title: "Landslide Alert",
    icon: Mountain,
    pageBg: "bg-amber-50",
    heroGradient: "from-stone-950 via-amber-800 to-orange-500",
    accent: "text-amber-100",
    panelBg: "bg-stone-950/80",
    meterCardBg: "bg-stone-950/84",
    readingCardBg: "bg-orange-950/70",
    infoStripBg: "bg-amber-100",
    infoStripBorder: "border-amber-200",
    infoStripText: "text-amber-900",
    sectionTint: "bg-amber-50",
    sectionBorder: "border-amber-200",
    meterLabel: "Slope Risk",
    meterUnit: "%",
    thresholdLabel: "Critical Risk",
    meterColor: "bg-orange-400",
    primaryReading: "Soil Moisture",
    primaryUnit: "%",
    secondaryReading: "Ground Movement",
    secondaryUnit: "mm/h",
    headline: "Slope stability is being watched closely.",
    description:
      "This view highlights live-style instability readings, danger thresholds, and public safety instructions for landslide-prone locations.",
    publicTips: [
      "Stay away from steep slopes and cracked ground.",
      "Leave immediately if you notice falling debris or soil movement.",
      "Avoid roads near unstable hill areas.",
    ],
  },

  wildfire: {
    key: "wildfire",
    title: "Wildfire Alert",
    icon: Flame,
    pageBg: "bg-red-50",
    heroGradient: "from-red-950 via-orange-800 to-yellow-500",
    accent: "text-orange-100",
    panelBg: "bg-red-950/82",
    meterCardBg: "bg-red-950/85",
    readingCardBg: "bg-orange-900/70",
    infoStripBg: "bg-red-100",
    infoStripBorder: "border-red-200",
    infoStripText: "text-red-900",
    sectionTint: "bg-red-50",
    sectionBorder: "border-red-200",
    meterLabel: "Fire Intensity",
    meterUnit: "%",
    thresholdLabel: "Critical Intensity",
    meterColor: "bg-orange-500",
    primaryReading: "Temperature",
    primaryUnit: "°C",
    secondaryReading: "Smoke Density",
    secondaryUnit: "%",
    headline: "Fire spread conditions remain under watch.",
    description:
      "This page shows live-style heat and smoke conditions, threat level, and the most important public actions to take.",
    publicTips: [
      "Move away from smoke and follow evacuation guidance immediately.",
      "Keep exit routes clear and be ready to leave quickly.",
      "Close doors and windows if smoke becomes heavy nearby.",
    ],
  },

  storm: {
    key: "storm",
    title: "Storm Alert",
    icon: CloudLightning,
    pageBg: "bg-indigo-50",
    heroGradient: "from-slate-950 via-indigo-900 to-blue-500",
    accent: "text-indigo-100",
    panelBg: "bg-slate-950/82",
    meterCardBg: "bg-slate-950/86",
    readingCardBg: "bg-indigo-950/70",
    infoStripBg: "bg-indigo-100",
    infoStripBorder: "border-indigo-200",
    infoStripText: "text-indigo-900",
    sectionTint: "bg-indigo-50",
    sectionBorder: "border-indigo-200",
    meterLabel: "Storm Intensity",
    meterUnit: "%",
    thresholdLabel: "Severe Level",
    meterColor: "bg-indigo-400",
    primaryReading: "Wind Speed",
    primaryUnit: "km/h",
    secondaryReading: "Rainfall",
    secondaryUnit: "mm",
    headline: "Severe weather conditions are active.",
    description:
      "This page shows live-style wind and rainfall conditions together with the current hazard level and safety guidance.",
    publicTips: [
      "Stay indoors and away from windows.",
      "Avoid unnecessary travel until conditions improve.",
      "Secure loose outdoor items where possible.",
    ],
  },

  cyclone: {
    key: "cyclone",
    title: "Cyclone Alert",
    icon: Wind,
    pageBg: "bg-cyan-50",
    heroGradient: "from-slate-950 via-cyan-900 to-sky-500",
    accent: "text-cyan-100",
    panelBg: "bg-slate-950/82",
    meterCardBg: "bg-slate-950/86",
    readingCardBg: "bg-cyan-950/70",
    infoStripBg: "bg-cyan-100",
    infoStripBorder: "border-cyan-200",
    infoStripText: "text-cyan-900",
    sectionTint: "bg-cyan-50",
    sectionBorder: "border-cyan-200",
    meterLabel: "Cyclone Strength",
    meterUnit: "%",
    thresholdLabel: "Severe Level",
    meterColor: "bg-cyan-400",
    primaryReading: "Wind Speed",
    primaryUnit: "km/h",
    secondaryReading: "Pressure Drop",
    secondaryUnit: "hPa",
    headline: "Cyclone conditions are intensifying.",
    description:
      "This page highlights live-style cyclone readings and what affected communities should do to stay safe.",
    publicTips: [
      "Remain indoors and follow official evacuation instructions.",
      "Stay away from coastal and exposed low-lying areas.",
      "Keep emergency supplies and phones ready.",
    ],
  },

  tsunami: {
    key: "tsunami",
    title: "Tsunami Alert",
    icon: Waves,
    pageBg: "bg-teal-50",
    heroGradient: "from-blue-950 via-teal-800 to-cyan-500",
    accent: "text-teal-100",
    panelBg: "bg-slate-950/82",
    meterCardBg: "bg-slate-950/86",
    readingCardBg: "bg-teal-950/70",
    infoStripBg: "bg-teal-100",
    infoStripBorder: "border-teal-200",
    infoStripText: "text-teal-900",
    sectionTint: "bg-teal-50",
    sectionBorder: "border-teal-200",
    meterLabel: "Wave Threat",
    meterUnit: "%",
    thresholdLabel: "Critical Threat",
    meterColor: "bg-teal-400",
    primaryReading: "Sea Level Change",
    primaryUnit: "m",
    secondaryReading: "Wave Speed",
    secondaryUnit: "km/h",
    headline: "Coastal hazard conditions are being monitored.",
    description:
      "This page shows live-style coastal threat conditions, current readings, and immediate safety actions for the public.",
    publicTips: [
      "Move immediately to higher ground away from the coast.",
      "Do not stay near beaches, river mouths, or sea walls.",
      "Use official evacuation routes without delay.",
    ],
  },

  drought: {
    key: "drought",
    title: "Drought Alert",
    icon: ThermometerSun,
    pageBg: "bg-yellow-50",
    heroGradient: "from-yellow-950 via-amber-800 to-orange-500",
    accent: "text-yellow-100",
    panelBg: "bg-yellow-950/82",
    meterCardBg: "bg-yellow-950/86",
    readingCardBg: "bg-amber-900/70",
    infoStripBg: "bg-yellow-100",
    infoStripBorder: "border-yellow-200",
    infoStripText: "text-yellow-900",
    sectionTint: "bg-yellow-50",
    sectionBorder: "border-yellow-200",
    meterLabel: "Drought Severity",
    meterUnit: "%",
    thresholdLabel: "Severe Stress",
    meterColor: "bg-yellow-400",
    primaryReading: "Temperature",
    primaryUnit: "°C",
    secondaryReading: "Water Reserve",
    secondaryUnit: "%",
    headline: "Dry conditions and water stress are active.",
    description:
      "This page shows live-style drought conditions and practical guidance for communities in affected areas.",
    publicTips: [
      "Conserve water and follow local restrictions.",
      "Avoid unnecessary outdoor activity during peak heat.",
      "Monitor local announcements on supply conditions.",
    ],
  },

  heatwave: {
    key: "heatwave",
    title: "Heatwave Alert",
    icon: ThermometerSun,
    pageBg: "bg-orange-50",
    heroGradient: "from-orange-950 via-red-800 to-yellow-500",
    accent: "text-orange-100",
    panelBg: "bg-orange-950/82",
    meterCardBg: "bg-orange-950/86",
    readingCardBg: "bg-red-900/70",
    infoStripBg: "bg-orange-100",
    infoStripBorder: "border-orange-200",
    infoStripText: "text-orange-900",
    sectionTint: "bg-orange-50",
    sectionBorder: "border-orange-200",
    meterLabel: "Heat Risk",
    meterUnit: "%",
    thresholdLabel: "Danger Level",
    meterColor: "bg-red-400",
    primaryReading: "Temperature",
    primaryUnit: "°C",
    secondaryReading: "Humidity",
    secondaryUnit: "%",
    headline: "Extreme heat conditions are being monitored.",
    description:
      "This page shows live-style heat stress conditions and the public precautions needed during a heatwave.",
    publicTips: [
      "Stay hydrated and avoid direct sun exposure.",
      "Reduce outdoor activity during the hottest hours.",
      "Check on children, elderly people, and vulnerable persons.",
    ],
  },

  earthquake: {
    key: "earthquake",
    title: "Earthquake Alert",
    icon: AlertTriangle,
    pageBg: "bg-stone-50",
    heroGradient: "from-black via-stone-800 to-slate-500",
    accent: "text-stone-100",
    panelBg: "bg-black/82",
    meterCardBg: "bg-black/86",
    readingCardBg: "bg-stone-900/70",
    infoStripBg: "bg-stone-100",
    infoStripBorder: "border-stone-200",
    infoStripText: "text-stone-900",
    sectionTint: "bg-stone-50",
    sectionBorder: "border-stone-200",
    meterLabel: "Seismic Risk",
    meterUnit: "%",
    thresholdLabel: "Danger Zone",
    meterColor: "bg-stone-400",
    primaryReading: "Aftershock Index",
    primaryUnit: "%",
    secondaryReading: "Ground Activity",
    secondaryUnit: "µm/s",
    headline: "Ground activity remains under observation.",
    description:
      "This page highlights live-style seismic conditions, aftershock-related risk, and key public safety actions.",
    publicTips: [
      "Stay away from damaged buildings and unstable structures.",
      "Be prepared for aftershocks.",
      "Follow official evacuation and safety advice.",
    ],
  },

  volcanic: {
    key: "volcanic",
    title: "Volcanic Activity Alert",
    icon: Volcano,
    pageBg: "bg-zinc-50",
    heroGradient: "from-black via-red-950 to-orange-600",
    accent: "text-orange-100",
    panelBg: "bg-black/82",
    meterCardBg: "bg-black/86",
    readingCardBg: "bg-red-950/70",
    infoStripBg: "bg-zinc-100",
    infoStripBorder: "border-zinc-200",
    infoStripText: "text-zinc-900",
    sectionTint: "bg-zinc-50",
    sectionBorder: "border-zinc-200",
    meterLabel: "Eruption Risk",
    meterUnit: "%",
    thresholdLabel: "Critical Level",
    meterColor: "bg-red-500",
    primaryReading: "Ash Density",
    primaryUnit: "%",
    secondaryReading: "Ground Tremor",
    secondaryUnit: "µm/s",
    headline: "Volcanic conditions are elevated.",
    description:
      "This page shows live-style volcanic activity conditions, risk level, and essential public guidance.",
    publicTips: [
      "Avoid ash-affected zones and follow exclusion guidance.",
      "Use face covering if ash is present.",
      "Prepare for rapid evacuation if instructed.",
    ],
  },

  blizzard: {
    key: "blizzard",
    title: "Blizzard Alert",
    icon: Snowflake,
    pageBg: "bg-slate-50",
    heroGradient: "from-slate-950 via-blue-900 to-slate-300",
    accent: "text-slate-100",
    panelBg: "bg-slate-950/82",
    meterCardBg: "bg-slate-950/86",
    readingCardBg: "bg-blue-950/70",
    infoStripBg: "bg-slate-100",
    infoStripBorder: "border-slate-200",
    infoStripText: "text-slate-900",
    sectionTint: "bg-slate-50",
    sectionBorder: "border-slate-200",
    meterLabel: "Blizzard Severity",
    meterUnit: "%",
    thresholdLabel: "Critical Cold",
    meterColor: "bg-sky-300",
    primaryReading: "Snowfall",
    primaryUnit: "cm",
    secondaryReading: "Wind Chill",
    secondaryUnit: "°C",
    headline: "Snowstorm conditions remain severe.",
    description:
      "This page shows live-style winter hazard conditions and important safety guidance for affected people.",
    publicTips: [
      "Avoid travel unless essential.",
      "Stay indoors and protect against extreme cold.",
      "Keep emergency heating and supplies ready.",
    ],
  },

  default: {
    key: "default",
    title: "Natural Disaster Alert",
    icon: CloudRain,
    pageBg: "bg-slate-50",
    heroGradient: "from-slate-950 via-slate-800 to-slate-500",
    accent: "text-slate-100",
    panelBg: "bg-slate-950/82",
    meterCardBg: "bg-slate-950/86",
    readingCardBg: "bg-slate-900/70",
    infoStripBg: "bg-slate-100",
    infoStripBorder: "border-slate-200",
    infoStripText: "text-slate-900",
    sectionTint: "bg-slate-50",
    sectionBorder: "border-slate-200",
    meterLabel: "Risk Level",
    meterUnit: "%",
    thresholdLabel: "Danger Level",
    meterColor: "bg-slate-400",
    primaryReading: "Primary Reading",
    primaryUnit: "",
    secondaryReading: "Secondary Reading",
    secondaryUnit: "",
    headline: "Hazard conditions are being monitored.",
    description:
      "This page presents live-style alert readings, public-facing status information, and safety guidance.",
    publicTips: [
      "Follow official instructions carefully.",
      "Stay informed using trusted updates.",
      "Avoid unnecessary travel in the affected area.",
    ],
  },
};

export function getDisasterTypeKey(type = "") {
  const value = String(type).trim().toLowerCase();

  if (value.includes("flood")) return "flood";
  if (value.includes("landslide")) return "landslide";
  if (value.includes("fire") || value.includes("wildfire")) return "wildfire";
  if (value.includes("storm")) return "storm";
  if (value.includes("cyclone")) return "cyclone";
  if (value.includes("tsunami")) return "tsunami";
  if (value.includes("drought")) return "drought";
  if (value.includes("heat")) return "heatwave";
  if (value.includes("earthquake")) return "earthquake";
  if (value.includes("volcan")) return "volcanic";
  if (value.includes("blizzard") || value.includes("snow")) return "blizzard";

  return "default";
}